# Generated by Django 5.0.6 on 2024-06-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('car_company', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('seater', models.IntegerField()),
            ],
        ),
    ]
